### ISSUE TITLE
Training the score network

### ISSUE THREAD

**Issue by Mithrandir117** [utcsilab/csgm-mri-langevin#2]
Hi, congratulations on this great work! I am trying to train the score network as you/your reference described in the paper, but I am running into out of memory issues (I am using a Quadro RTX 8000 with 45GB of memory). My dataset is 2D image slices of shape (208,240). The only way I can fit the training on memory is to reduce the ngf of the configuration file to 30 from 128 (I believe this is related to the number of channels of the convolutions in the blocks of the network?). I was hoping maybe you could shed some light on this/how you trained your network. Best regards, Thomas Yu

**Comment by mariusarvinte** [comment]
Hi, indeed _ngf_ controls the number of channels after the first hidden layer, thus will linearly impact the used VRAM.

What is the batch size you are using? Training with 384 x 384 complex (2-channel) 2D images with batch size = 1 should fit in 32 GB VRAM, so yours should fit as well. Is it possible you're using a too large of a batch size?

**Comment by Mithrandir117** [comment]
Yes! Sorry, I completely glossed over this; I assumed that in the paper where it says that you use the FFHQ config with just the sigma changed, that you used the batch size there as well.  Indeed this fixes the problem. Thank you!
