### ISSUE TITLE
checkpoint_100000.pth

### ISSUE THREAD

**Issue by Mahdisbr77** [utcsilab/csgm-mri-langevin#6]
Hello Dear team,
I was looking at your code and tried to implement on my dataset with fewer samples. But, I couldn't find the checkpoint_100000.pth weights in order to train my model. Did I make a mistake or you didn't provide the weights for public?

Thanks in advance,
Mahdi

**Comment by ajiljalal** [comment]
Hello

Were you able to successfully run the following command to download the checkpoint ? (please run it from the csgm-mri-langevin directory)

gdown https://drive.google.com/uc?id=1vAIXf8n67yEAPmH2I9qiDWzmq9fGKPYL

Once it's downloaded, running 
tar -zxvf checkpoint.tar.gz
should extract the model

**Comment by Mahdisbr77** [comment]
Thanks. That helped a lot.
